version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Changed from 80:80 
    environment:
      - NODE_ENV=production
    restart: unless-stopped
