import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto bg-white shadow-lg rounded-2xl p-6 sm:p-10 space-y-12">
        <header>
          <h1 className="text-5xl sm:text-4xl font-semibold text-[#2E4168] text-center mb-8">
            Terms and Conditions
          </h1>
          <p className="text-gray-600 text-base sm:text-lg">
            These Terms and Conditions govern your use of the services provided by GudMed at gudmed.in.
          </p>
        </header>

        <Section
          title="Introduction"
          items={[
            `The following are the Terms and Conditions, read together with the Privacy Policy, that govern your purchase and use of the services from gudmed.in, and constitute a legally binding agreement, between you ("the Customer", the "User" or "the Caregiver") and gudmed.com, a fully licensed Pharmacy.`,
            `In terms of Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures.`,
            `This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of https://www.gudmed.in/ or the application ‘GudMed -HealthCare Simplified.’`,
            `The domain name “https://www.gudmed.in” (hereinafter referred to as ‘Website’) is registered under “GUD MEDICARE SOLUTIONS PRIVATE LIMITED” with the address at House No. 979 Block-E Landmark Opp Kailash Enclave Gate Saraswati Vihar Pitampura – 110034 (hereinafter referred to as ‘Company’).`,
            `For the purpose of these Terms of Service, wherever the context so requires, the term ‘You’/‘User’ shall mean any natural or legal person who uses the website and provided Registration Data while registering on the website or simply visiting by entering the domain name in any internet browser. Any services provided by the Website which do not require registration do not absolve you of the contractual relationship established by this Agreement.`,
            `Wherever the context requires, the term ‘Doctor/registered medical practitioners’ shall mean any person permitted to practice medicine by the MCI (Medical Council of India) or any regional council for registration of Doctor/registered medical practitioners duly authorized by the government who will be verified and authenticated by us.`,
            `By browsing and using the website, you are bound by these Terms of Service and any other binding document as decided by the Company. You are requested to read them carefully before accepting the same and moving forward to using the Website.`,
            `By visiting, viewing, accessing or otherwise using any of the services or information created, collected, compiled or submitted to www.gudmed.in, you are deemed to have agreed to all the following Terms and Conditions of Service. So, before you use this Website, please read these Terms carefully as you agree to be bound by them. If you do not accept these Terms and Conditions, please do not use this Website.`,
          ]}
        />

        <Section
          title="1. CREATING AN ACCOUNT"
          items={[
            `1.1 To use certain features of the Website (e.g., user profile, posting rating/reviews, receiving GudMed newsletters), you must set up an account with gudmed.in ("GudMed Account") and provide certain information about yourself as prompted by the Customer Information form, including your name, gender, email address, account password, mobile phone number, and billing address. All of your registration information is protected by our Privacy Policy.`,
            `1.2 You represent and warrant that the information you submit during registration is truthful and accurate and that you will maintain the accuracy of such information.`,
            `1.3 Your GudMed Account username and password are personal to you. You may not transfer your account and you will be responsible for the activities associated with your GudMed Account.`,
            `1.4 gudmed.in will not be liable for any loss or damages as a result of your failure to maintain the confidentiality of your account credentials. If you suspect any unauthorized use of your GudMed account, you shall immediately notify gudmed.in.`,
            `1.5 It is your responsibility to keep your email address up-to-date on your account setup at gudmed.in so that we can communicate with you electronically.`,
            `1.6 By creating this account, you agree to receive transactional and/or promotional communications from us via email, telephone, SMS, WhatsApp, and chat. If you, at any time, wish to discontinue receiving communications from us, you agree to notify us by email.`,
            `1.7 By using a GudMed account, you need to get verified through SMS or WhatsApp.`,
            `1.8 Customers need to send their prescription by using WhatsApp, and you will be responsible for all health-based information shared with us through WhatsApp.`,
          ]}
          //isBulletList
        />

        <Section
          title="2. PRIVACY POLICY"
          items={[
            `2.1 Your personally identifiable information will be used in accordance with our Privacy Policy. To understand our practices, as to how we collect, use, and disclose your personally identifiable information, please refer to our Privacy Policy, which also governs your visit to gudmed.in.`,
            `2.2 We understand the privacy of all information you provide is of primary importance. This is why we do everything possible to use it carefully and sensibly. This information is never shared with other companies or third-party service providers.`,
          ]}
         // isBulletList
        />

        <Section
          title="3. COMMUNICATIONS"
          items={[
            `By using the Website or WhatsApp, it is deemed that you have consented to receiving calls, auto-dialed and/or pre-recorded messages or calls, from us at any time with the use of the telephone number that has been provided by you for the use of this Website, subject to the Privacy Policy. This includes contacting you through information received through other parties as well as contacting other parties through the information provided by you. By using this Website, you—who has requested service with us, or has only signed up, or submitted your personal details in any of our forms—also consent to receive transactional and/or promotional emails/SMSs from us at any time we deem fit. This consent to be contacted is for purposes that include and are not limited to clarification calls and marketing and promotional calls and messages. In case you wish to stop contact with us for the same, you may send us a mail to cs@gudmed.in. You may also be contacted through WhatsApp or Facebook Messenger. You need to share your ID, phone number, verify yourself by using 2-factor verification, and you are done!`,
            `You may also be contacted by Service Providers with whom we have entered into a contract in furtherance of our rights, duties, and obligations under other agreements, contracts, and policies followed by us. Such contact will be made only in pursuance of the respective contracts, agreements, and/or policies.`,
            `The sharing of the information provided by you will be governed by the Privacy Policy. We will not give out your contact information to third parties not connected with the Website and the services offered by it, and/or for any purpose not in furtherance of the activities and aims of the Company. Please refer to the 'Privacy Policy' for more information.`,
          ]}
          //isBulletList
        />

        <Section
          title="4. SECURITY POLICY"
          items={[
            `4.1 All your transactions are secure when you submit a request for the prescription translation service at gudmed.in. Your personal information is encrypted by using 256-bit Secure Sockets Layer (SSL) encryption technology before being sent over the Internet, which ensures the privacy and high level of security of all your information.`,
            `4.2 All shared or uploaded data will be under HIPAA-compliant data centers and ISO 27001 certified.`,
            `4.3 Data privacy and security have always served as one of the foundations of GudMed. And we ensure you about the safety of your data.`,
          ]}
         // isBulletList
        />

        <Section
          title="5. CUSTOMER MEMBERSHIP/USAGE/ELIGIBILITY"
          items={[
            `The membership/usage of the Website is restricted to those above 18 years of age, or to such group that can be termed to have attained 'majority' under the laws of the respective jurisdictions where this Website can be seen and is accessible or free from social minors, who possess legal parental or guardian consent, or are in a position so as to be fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service.`,
            `Further, you are solely responsible for protecting the confidentiality of your username and password, and any activity under the account will be deemed to have been done by you. In the case that you provide us with false and inaccurate details or the Company has reasonable reasons to believe you have done so, we hold the rights to suspend your account and/or terminate this Agreement without any notice and without being held liable for the same.`,
            `You understand the website you use on your phone, computer, or tablet is owned by us, and we may automatically upgrade the website, and these Terms shall apply to the upgrades as well. We reserve the right to terminate this agreement without any notice and suspend the account without assigning any reason.`,
          ]}
        //  isBulletList
        />

        <Section
          title="6. USE OF INFORMATION ON THE WEBSITE"
          items={[
            `6.1 The information on this Website is not a substitute for professional medical advice or treatment for specific medical conditions. It is important that you do not make medical decisions, and you should always seek advice from a qualified healthcare professional with any questions you may have about your medical condition.`,
            `6.2 Gudmed.in does not endorse any views or opinions that may be included in the Website Content or other information provided through our Services. Your submission of questions or reviews on our Services does not constitute a professional relationship between you and Gudmed.in.`,
          ]}
          //isBulletList
        />

        <Section
          title="7. USER OBLIGATIONS"
          items={[
            `You are a restricted user of this Website.`,
            `7.1 You are bound not to cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post, publish, or create derivative works from, transfer, or sell any information or software obtained from the Website. With our prior permission, limited use may be allowed. Copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information within the content of the Website is not permitted. You shall not, nor allow third parties on your behalf to (i) make and distribute copies of the Website, (ii) attempt to copy, reproduce, alter, modify, reverse engineer, disassemble, decompile, transfer, exchange, or translate the Website, or (iii) create derivative works of the Website of any kind whatsoever.`,
            `7.2 This Website by nature allows you to upload information; you undertake to ensure that such material is in accordance with applicable laws. Further, you undertake not to:`,
            `a) Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean, or otherwise violate the legal rights of others;`,
            `b) Engage in any activity that interferes with or disrupts access to the Website or the Services (or the servers and networks which are connected to the Website);`,
            `c) Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;`,
            `d) Publish, post, disseminate any information which is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;`,
            `e) Post any file that infringes the copyright, patent, or trademark of other legal entities;`,
            `f) Upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Website;`,
            `g) Download any file posted by another user of a Service that you know, or reasonably should know, cannot be legally distributed in such manner;`,
            `i) Disrupt or interfere with the security of, or otherwise cause harm to, the Website, systems resources, accounts, passwords, servers, or networks connected to or accessible through the Website or any affiliated or linked sites;`,
            `j) Collect or store data about other users in connection with the prohibited conduct and activities set forth in this Section;`,
            `k) Use the Website or any material or Content for any purpose that is unlawful or prohibited by these Terms of Service, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website or other third parties;`,
            `l) Violate any code of conduct or other guidelines, which may be applicable for or to any particular Service;`,
            `m) Violate any applicable laws or regulations for the time being in force within or outside India;`,
            `n) Violate the Terms of Service including but not limited to any applicable Additional Terms of the Website contained herein or elsewhere;`,
            `o) Violate any code of conduct or other guidelines, which may be applicable for or to any particular Service;`,
            `p) Threaten the unity, integrity, defense, security, or sovereignty of India, friendly relations with foreign states, or public order or cause incitement to the commission of any cognizable offence or prevent investigation of any offence or insult any other nation;`,
            `q) Publish, post, disseminate information that is false, inaccurate, or misleading; violate any applicable laws or regulations for the time being in force in or outside India;`,
            `r) Directly or indirectly, offer, attempt to offer, trade, or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation, or guideline for the time being in force;`,
            `s) Create liability for us or cause us to lose (in whole or in part) the services of our internet service provider ("ISPs") or other suppliers.`,
            `While we shall not be held liable or answerable to Users for any such acts on your part, violation of this clause would lead to potential criminal legal action against you, either by other Users of the Website or by us.`,
            `We can (and you hereby expressly authorize us to) disclose any information about you to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury. You understand that we have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website) as necessary to satisfy any law, regulation, or valid governmental request. This may include, without limitation, disclosure of the information in connection with the investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order.`,
            `We have no obligation to monitor the material posted on the Website. We shall have the right to remove or edit any content, testimonials, or reviews that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Service. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE. You hereby represent and warrant that you have all necessary rights in and to all Content which you provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortuous, or otherwise unlawful information.`,
          ]}
          //isBulletList
        />

        <Section
          title="8. DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY"
          items={[
            `8.1 All information and services included on or otherwise made available to you through this Website are provided by gudmed.in on an "as is" and "as available" basis, either expressed or implied, we specifically disclaim warranties of any kind to the extent allowed by the applicable law. You expressly agree that your use of this Website is at your sole risk.`,
            `8.2 Gudmed.in assumes no responsibility for any damages or viruses that may infect your computer equipment or other property on account of your access to, use of, or browsing in this site.`,
            `8.3 Gudmed.in has exerted reasonable efforts to ensure that all information published on the Website is accurate at the time of posting; however, there may be errors in such information for which we shall have no liability. We reserve the right to remove or alter any of the information contained on the Website at our sole discretion.`,
            `8.4 Gudmed.in cannot guarantee the adequacy or completeness of the Website content. Gudmed.in does not warrant or endorse the effectiveness.`,
            `8.5 We disclaim responsibility for any harm to persons resulting from any instructions or products referred to in the Website. Gudmed.in is not associated with any manufacturer of medicines or other products on the Website. We do not warrant that the Website or its content will meet your requirements.`,
            `8.6 Gudmed.in reserves the right to modify or withdraw any part of the website or any of its content at any time without notice.`,
          ]}
          //isBulletList
        />

        <Section
          title="9. WEBSITE AVAILABILITY"
          items={[
            `We take all reasonable care to ensure the availability of the Gudmed.in Website 24 hours every day, 365 days per year. However, the Website may become temporarily unavailable due to maintenance, server, or other technical issues, or for reasons beyond our control. Gudmed.in does not warrant uninterrupted access to this Website or any linked website. However, we may, but shall not be obliged to, issue a notice when we know of scheduled maintenance of our Website.`,
          ]}
         // isBulletList
        />

        <Section
          title="10. PRESCRIPTION MEDICATION POLICY"
          items={[
            `10.1 Gudmed.in, a fully licensed and regulated pharmacy, takes all precautions to strictly abide by the laws and regulations set forth in the dispensing of prescription medications. By requesting the prescription translation for your medicines, you acknowledge and accept the following terms regarding the service of any prescription medicines.`,
            `10.2 Gudmed.in will not serve any prescription medication for translation without a valid prescription from a licensed physician.`,
            `10.3 If you are asking for a prescription to get it translated, you hereby confirm that you will send us a scanned copy of your valid prescription(s) via email, WhatsApp, Facebook Messenger, Telegram, or Signal, and this prescription shall then be subject to the examination and approval by our qualified Pharmacists.`,
            `10.4 If our pharmacists have any questions or concerns about the prescription(s), you hereby authorize them to consult with an external network of doctors about the validity of the prescription.`,
            `10.5 The drug information provided in Gudmed.in is for informative purposes only, and this Website is not intended to provide diagnosis, treatment, or medical advice. We are not liable for any adverse effects or harm to you as a result of your reliance on the information in the Website.`,
            `10.6 GudMed requires either the User, Customer, or Caregiver to confirm he/she is completely aware of the indications, side effects, drug interactions, effects of missed dose, or overdose of the medicines he/she orders from us.`,
            `10.7 At Gudmed.in, a Caregiver can ask for prescription translation of medicines on your behalf.`,
          ]}
          //isBulletList
        />

        <Section
          title="11. LOCATION"
          items={[`Currently, we provide Chat and Phone call services in India. For the same, please contact us at cs@gudmed.in.`]}
        />

        <Section
          title="12. COPYRIGHTS, TRADEMARKS, AND OTHER INTELLECTUAL PROPERTY RIGHTS"
          items={[
            `12.1 As per the Terms and Conditions of Gudmed.in, the Website grants access to Users/Customers to view the content solely for visiting, knowledge, and communicating only. All services in this Website, including, but not limited to, images, illustrations, text, logos, and page headers, that are part of this Website are copyrights and other intellectual properties owned by Gud Medicare Solutions Private Limited. GudMed operates this operation under HIPAA Compliances.`,
            `12.2 You hereby agree that you will not reproduce, duplicate, or copy the content of Gudmed.in for any purpose, unless you have been specifically permitted to do so in a separate agreement with this Website.`,
          ]}
          //isBulletList
        />

        <Section
          title="13. SEVERABILITY"
          items={[`If any provision of these Terms and Conditions shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and Conditions and shall not affect the validity and enforceability of any remaining provisions.`]}
        />

        <Section
          title="14. TERMINATION"
          items={[
            `You agree that Gudmed.in, in its sole discretion and for any or no reason, including without limitation if you breach these Terms and Conditions, may terminate your access to and use of the Website, at any time. You agree that any termination of your access to the Website or suspension of your account may be effected without prior notice, and you agree that gudmed.in shall not be liable to you for any such termination. Your right to use the GudMed Website/Service immediately ceases upon termination of your access/use of the Website.`,
          ]}
        />

        <Section
          title="15. CHANGES TO THESE TERMS AND CONDITIONS"
          items={[
            `We reserve the right to amend these terms and conditions from time to time without further notice to you. Any such amendments we make shall be effective once we post a revised version of these Terms and Conditions on the Website. It is your responsibility to review the Gudmed.in’s Terms and Conditions regularly. Your continued use of the Website following the publication of any such changes will constitute your agreement to follow and be automatically bound by the amended terms and conditions.`,
          ]}
        />

<Section
  title="Contact Information"
  items={[
    <>
      Gud Medicare Solutions Private Limited. GudMed. Contact us at{' '}
      <a href="mailto:cs@gudmed.in" className="text-[#2E4168] text-lg">
        cs@gudmed.in
      </a>.
    </>
  ]}
/>

      </div>
    </div>
  );
};

function Section({ title, items, isBulletList = false }) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl sm:text-2xl font-semibold text-[#2E4168]">{title}</h2>
      <div className="space-y-2 text-black  text-sm sm:text-base leading-relaxed">
        {isBulletList ? (
          <ul className="list-disc pl-6 space-y-1">
            {items.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        ) : (
          items.map((item, index) => <div key={index}>{item}</div>)
        )}
      </div>
    </section>
  );
}

export default TermsAndConditions;